module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      'white': '#ffffff',
      'black': '#000000',
      "darkBlack": "#060e0c",
      'darkGreen': '#19352A',
      'primary': '#007683',
      'secondary': '#5fbb97',
      'secondaryLight': '#8ddca4',
      'gray': '#F7F7F7',
      'hrgray': '#908d8d',
      'placeholderGray': '#A9A9AC',
      'darkGray': '#EBEBEB',
      'yellow': '#FFC000',
      'grey': '#757474',
      'green': '#3F2D66',
      'orange': '#FFE081',
      'grayToggle': '#808080',
      'btnColor': '#E8E8E8',
    },
  },
  plugins: [],
};
